### ISSUE TITLE
about code/data

### ISSUE THREAD

**Issue by chuxuzhang** [THU-KEG/MetaKGR#2]
It seems that test data in github is not consistent with that in the paper. 
Could you provide the train/test data which can reproduce the results reported in Table 1?
It would be great if you can provide some checkpoint information (e.g., how many epochs in training and adaptation) to reproduce the results in the paper.
Thanks a lot.

**Comment by davidlvxin** [comment]
The test data in github is used for K=max setting, which is also used for Table 1.

Since the code and output files are not well organized, I can't find the exact checkpoint information. But I can still give the following information from my memory:

FB15K237: 
Training epoch: 15 or 25
Adaptation epoch: 39

NE:
Training epoch: 40
Adaptation epoch: 40

Please feel free to contact me here if you have more questions.

**Comment by chuxuzhang** [comment]
Thanks for quick reply.
The triple number in test data of FB in github is 668 while the test data of whole data in paper seems to be around 4k (raw data - training data). Could you double check it? Let me know if I made mistake.

**Comment by davidlvxin** [comment]
4k is not the number of test data, but the numbet of few-shot triples in train data.
